before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
    ldflags:
      - -s -w -X main.Version={{.Version}}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
- image_templates:
    - "ghcr.io/minetest-go/mapcleaner:{{ .Version }}"
    - "ghcr.io/minetest-go/mapcleaner:latest"
  dockerfile: Dockerfile