version: "3.6"

services:
 sut:
  build:
   context: .
   dockerfile: ./Dockerfile.test
  user: root
  working_dir: /root/.minetest/worlds/world
  volumes:
    - "./test/testmod:/root/.minetest/worlds/world/worldmods/testmod/"
    - "./test/world.mt:/root/.minetest/worlds/world/world.mt"
    - "./test/minetest.conf:/minetest.conf"
