# mapcleaner build
FROM golang:1.19.0 as builder
COPY ./ /app
WORKDIR /app
RUN go test ./... &&\
  go build

# minetest
FROM registry.gitlab.com/minetest/minetest/server:5.6.1

USER root
RUN apk add git sqlite3 &&\
    mkdir -p /root/.minetest/worlds/world/worldmods/ &&\
    git clone https://github.com/BuckarooBanzay/mtt /root/.minetest/worlds/world/worldmods/mtt &&\
    git clone https://github.com/minetest-mods/areas /root/.minetest/worlds/world/worldmods/areas

COPY --from=builder /app/mapcleaner /mapcleaner
COPY ./test/entrypoint.sh /entrypoint.sh
COPY ./test/mapcleaner.json /root/.minetest/worlds/world/
COPY ./test/mapcleaner_protect.txt /root/.minetest/worlds/world/
ENTRYPOINT /entrypoint.sh