name: jshint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: sudo apt-get install -y nodejs npm
    - name: install
      run: npm i
    - name: jshint
      run: npm run jshint
